# Generated by Django 5.0.4 on 2024-04-18 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="driver",
            field=models.ForeignKey(
                limit_choices_to={"usertype": "driver"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rides_as_driver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="rider",
            field=models.ForeignKey(
                limit_choices_to={"usertype": "rider"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rides_as_rider",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
