# Generated by Django 5.0.4 on 2024-04-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_alter_ride_driver_alter_ride_rider"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="current_location_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="current_location_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
