# Generated by Django 5.0.4 on 2024-04-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="usertype",
            field=models.CharField(
                choices=[("rider", "Rider"), ("driver", "Driver")], max_length=128
            ),
        ),
    ]
